### PR TITLE
Add some Kernel module

### PR DESCRIPTION
**Pull request by sum2012**
Fix black screen of Chinese version of Utawareru Mono
Loading still have problem
Modify log: https://gist.github.com/sum2012/58179ca7e1b8fbc8d58a

### CODE REVIEW

**Comment by Hykem** [comment]
Not sure about adding "sctrlHENSetStartModuleHandler", so I'll wait for @gid15 to take a look at this.

**Comment by sum2012** [comment]
21:00:23 ERROR      hle - GUI - Tried to register a second handler for NID 0xF9275D98 called sceKernelLoadModuleBufferUsbWlan

Let @gid15 find a good way to solve.
(I added ModuleMgrForKernel_a1a78c58 which is not in ModuleMgrForUser before)

**Comment by sum2012** [comment]
@Hykem There is a sample code of "sctrlHENSetStartModuleHandler"
in http://wololo.net/talk/viewtopic.php?f=5&t=1139

int module_start(SceSize args, void* argp)
{
   // Establish a handler that gets called before any modules "module_start" function is called.
   // A previous handler gets saved.
   previousStartModuleHandler = sctrlHENSetStartModuleHandler(on_module_start);

   return 0;
}

**Comment by Hykem** [comment]
Ok, after reviewing this for a while, I think it makes indeed sense to start adding some kernel related features. We should probably add a warning for CFW specific functions, but I'm merging this nonetheless.

**Comment by sum2012** [comment]
Thanks @Hykem

**Pull request merged**
