### PR TITLE
Add .gitignore. Have git ignore the followings:

### PR DESCRIPTION
**Pull request by pal1000**
-build cache;
-distribution folder;
-Settings file;
-external software renderer DLLs;
-virtual memory stick and UMD images except pre-existing content.

### CODE REVIEW

**Comment by pal1000** [comment]
This was only tested on Windows. Additional tweaks may be required for other platforms.

**Comment by gid15** [comment]
umdimages/cube.cso, umdimages/cube.iso and umdimages/iotest.iso should not be ignored.

**Comment by pal1000** [comment]
Per git documentation, .gitignore doesn't apply to files that are already tracked by git:
http://git-scm.com/docs/gitignore

**Comment by gid15** [comment]
OK, thank you for the hint.
Are the 3 exclusions under ms0/PSP/GAME then really needed?
!ms0/PSP/GAME/JpcspConnector/
!ms0/PSP/GAME/pong/
!ms0/PSP/GAME/SavedataTool/

**Comment by pal1000** [comment]
Yes, because .gitignore doesn't affect individual files already tracked by git, but not folders. Consider you want to make changes to any of these 3 tools, then the changes would get ignored if those exceptions would be removed.

**Comment by gid15** [comment]
Thank you for the details, I've never used git before...

**Pull request merged**
